apm-server:
  host: "0.0.0.0"
  rum:
    enabled: true
  auth.secret_token: ${KIBANA_SERVICE_ACCOUNT_TOKEN}

output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOST_PORT}"]
  username: "${ELASTIC_USERNAME}"
  password: "${ELASTIC_PASSWORD}"
  ssl:
    enabled: true
    certificate_authorities: ["/certs/ca.crt"]
    certificate: "/certs/apm-server.crt"
    key: "/certs/apm-server.key"
