---
## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.js
#
server.name: kibana
server.host: "0.0.0.0"
server.publicBaseUrl: "https://elastic.solidchain.xyz"

# Elasticsearch Connection
elasticsearch.hosts: [ "${ELASTICSEARCH_HOST_PORT}" ]

# SSL settings
server.ssl.enabled: true
server.ssl.certificate: /certs/kibana.crt
server.ssl.key: /certs/kibana.key
server.ssl.certificateAuthorities: [ "/certs/ca.crt" ]
xpack.security.encryptionKey: jhuXWoqebMuqRiy8rCKc2o5q1LCSXsmU1
xpack.encryptedSavedObjects.encryptionKey: G6F0PfCxaqYhDvUbqwv53pXuyRJfnFbIF
xpack.reporting.encryptionKey: P3M377LH8QPmFpHnpIfWFyCGiQUENlG25

## X-Pack security credentials
# cannot use both token + username passwords
elasticsearch.serviceAccountToken: "${KIBANA_SERVICE_ACCOUNT_TOKEN}"
elasticsearch.ssl.certificateAuthorities: [ "/certs/ca.crt" ]

## Default Agent policy integration
xpack.fleet.agents.enabled: false
# xpack.fleet.agents.fleet_server.hosts: ["${FLEET_SERVER_HOST_PORT}"]
# xpack.fleet.outputs:
#   - id: elasticsearch-1
#     name: default
#     type: elasticsearch
#     hosts: [ "${ELASTICSEARCH_HOST_PORT}" ]
#     is_default: true
#     is_default_monitoring: true
#     config:
#       username: "${ELASTIC_USERNAME}"
#       password: "${ELASTIC_PASSWORD}"
#       ssl:
#         verification_mode: full
#         certificate_authorities: ["/certs/ca.crt"]
#         certificate: "/certs/elastic-agent.crt"
#         key: "/certs/elastic-agent.key"

# Repo found: https://epr.elastic.co/search
# xpack.fleet.packages:
#   - name: system
#     version: latest
#   # - name: logstash
#   #   version : latest
#   - name: elastic_agent
#     version: latest
#   - name: apm
#     version: latest
#   - name: fleet_server
#     version : latest
# xpack.fleet.agentPolicies:
#   - name: Fleet Server 1
#     id: ${FLEET_POLICY_ID}
#     namespace: fleet
# #     monitoring_enabled:
# #       - logs
# #       - metrics
#     package_policies:
#       - name: system-1
#         id: default-system
#         package:
#           name: system
#         namespace: default
#       - name: apm-1
#         id: default-apm
#         package:
#           name: apm
#         namespace: default
#       - name: elastic_agent-1
#         id: default-agent
#         package:
#           name: elastic_agent
#         namespace: default
#       - name: fleet_server-1
#         id: default-fleet
#         package:
#           name: fleet_server
#         namespace: default
      # - name: logstash-1
      #   id: default-logstash
      #   package:
      #     name: logstash
      #   namespace: default

## Misc
elasticsearch.requestTimeout: 90000

## ElastAlert Plugin
#elastalert-kibana-plugin.serverHost: elastalert
#elastalert-kibana-plugin.serverPort: 3030